#!/usr/bin/env python3
"""
Generate test-assets/vocals-clean.wav and test-assets/fixtures.json
using macOS TTS (say -v Alice).

Each word is synthesised individually so we have exact start/end timestamps.
A 250 ms silence gap is inserted between words.
The final clip is zero-padded to 30 s.

Usage:
    cd /Users/lucazonta/Workspace/ColognaKaraokeTauri
    python3 scripts/gen-test-fixtures.py
"""

import json
import os
import struct
import subprocess
import sys
import tempfile
import wave

VOICE = "Alice"
SAMPLE_RATE = 16_000
SILENCE_MS = 250
OUT_DIR = "test-assets"
LYRICS = (
    "Dice che era un bell'uomo e veniva dal mare "
    "parlava un'altra lingua però sapeva amare "
    "e quel giorno lui prese mia madre sopra un bel prato"
)


def say_word(word: str, out_wav: str) -> None:
    """Synthesise a single word to a 16 kHz mono float-32 WAV."""
    subprocess.run(
        [
            "say",
            "-v", VOICE,
            "-o", out_wav,
            "--data-format=LEF32@{rate}".format(rate=SAMPLE_RATE),
            word,
        ],
        check=True,
        capture_output=True,
    )


def read_f32_wav(path: str) -> list[float]:
    """Read a 32-bit float WAV and return samples as Python floats."""
    with open(path, "rb") as f:
        data = f.read()
    # say outputs a headerless or minimal AIFF-C / WAV — parse carefully.
    # Try standard wave module first (works for WAV).
    try:
        with wave.open(path) as w:
            if w.getsampwidth() == 4:
                raw = w.readframes(w.getnframes())
                n = len(raw) // 4
                return list(struct.unpack(f"<{n}f", raw))
            else:
                # Fallback: 16-bit int → float
                raw = w.readframes(w.getnframes())
                n = len(raw) // 2
                ints = struct.unpack(f"<{n}h", raw)
                return [s / 32768.0 for s in ints]
    except Exception:
        # Fallback: raw float32 body after skipping WAV header (44 bytes).
        body = data[44:]
        n = len(body) // 4
        return list(struct.unpack(f"<{n}f", body[:n * 4]))


def write_s16_wav(path: str, samples: list[float], rate: int) -> None:
    clamped = [max(-1.0, min(1.0, s)) for s in samples]
    pcm = struct.pack(f"<{len(clamped)}h", *[int(s * 32767) for s in clamped])
    with wave.open(path, "w") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(pcm)


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    words = LYRICS.split()
    silence = [0.0] * int(SAMPLE_RATE * SILENCE_MS / 1000)

    print(f"Synthesising {len(words)} words with voice '{VOICE}' ...")

    word_samples: list[list[float]] = []
    with tempfile.TemporaryDirectory() as tmp:
        for i, word in enumerate(words):
            wav_path = os.path.join(tmp, f"w{i:03d}.wav")
            say_word(word, wav_path)
            samps = read_f32_wav(wav_path)
            word_samples.append(samps)
            print(f"  [{i+1:2d}/{len(words)}] {word:20s} → {len(samps)/SAMPLE_RATE*1000:.0f} ms")

    # Concatenate with silence gaps; record exact timestamps.
    all_samples: list[float] = []
    word_entries = []

    for word, samps in zip(words, word_samples):
        start = len(all_samples) / SAMPLE_RATE
        all_samples.extend(samps)
        end = len(all_samples) / SAMPLE_RATE
        all_samples.extend(silence)
        word_entries.append({"word": word, "start": round(start, 4), "end": round(end, 4)})

    speech_duration = len(all_samples) / SAMPLE_RATE

    # Pad to 30 s.
    target = SAMPLE_RATE * 30
    if len(all_samples) < target:
        all_samples.extend([0.0] * (target - len(all_samples)))
    else:
        all_samples = all_samples[:target]

    # Write WAV.
    wav_out = os.path.join(OUT_DIR, "vocals-clean.wav")
    write_s16_wav(wav_out, all_samples, SAMPLE_RATE)
    print(f"\nWrote {wav_out}  ({speech_duration:.1f}s speech, 30.0s total)")

    # Write fixtures.json.
    fixture = {
        "_comment": "Auto-generated by scripts/gen-test-fixtures.py via macOS TTS. Timestamps are exact.",
        "audio_file": "vocals-clean.wav",
        "duration_seconds": 30.0,
        "language": "it",
        "lyrics": LYRICS,
        "words": word_entries,
    }
    fix_out = os.path.join(OUT_DIR, "fixtures.json")
    with open(fix_out, "w", encoding="utf-8") as f:
        json.dump(fixture, f, indent=2, ensure_ascii=False)
    print(f"Wrote {fix_out}")

    print("\nTimestamps:")
    for e in word_entries:
        print(f"  {e['word']:20s} {e['start']:.3f}s – {e['end']:.3f}s")


if __name__ == "__main__":
    main()
